server:
  port: 8083

spring:
  application:
    name: gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  #需要忽略请求头部信息,不在传播到其它微服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers:  Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    bed: /bed/**
    customer: /common/**,/customer/**

ribbon:
  ReadTimeout: 120000  #请求处理的超时时间
  ConnectTimeout: 30000  #请求连接的超时时间
